name: Publish Package to npmjs
on:
  push:
    tags:
      - "cli-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build --workspace packages/clinder
      - run: npm publish --provenance --access public --workspace packages/clinder
